image: openjdk:11-stretch

stages:
  - test
  - build
  - deploy

before_script:
  - echo "Start CI/CD"

test:
  stage: test
  script: ./gradlew check

build:
  stage: build
  script: ./gradlew assemble

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_API_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
